theme = "tokyonight"

[editor]
line-number = "relative"
# mouse = false
continue-comments = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]

d = "delete_selection_noyank"
c = "change_selection_noyank"

"A-d" = "delete_selection"
"A-c" = "change_selection"


"A-k" = ["delete_selection", "move_line_up" ,"paste_before"]
"A-j" = ["delete_selection", "paste_after"]
